t_exception_propagation-x_declaration_parameter.adb:34:7: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:35:7: Error: declaration: declaration can propagate exceptions (declaration at level 1)
t_exception_propagation-x_declaration_parameter.adb:45:7: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:46:7: Error: declaration: declaration can propagate exceptions (declaration at level 2)
t_exception_propagation-x_declaration_parameter.adb:56:7: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Gen_Param: subprogram "Proc10" can propagate exceptions, used as call-back in instantiation at t_exception_propagation-x_declaration_parameter.adb:123:4
t_exception_propagation-x_declaration_parameter.adb:91:4: Error: Gen_Param: generic "Gen1" can propagate exceptions, instance "Inst1" at t_exception_propagation-x_declaration_parameter.adb:95:4 used as call-back in instantiation at t_exception_propagation-x_declaration_parameter.adb:124:4
t_exception_propagation-x_declaration_parameter.adb:126:4: Error: declaration: declaration can propagate exceptions (declaration at level 3)
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param10: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:130:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param11: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:136:4
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param11: subprogram "Proc11" can propagate exceptions (declaration at level 1), used as call-back at t_exception_propagation-x_declaration_parameter.adb:137:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param12: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:142:4
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param12: subprogram "Proc11" can propagate exceptions (declaration at level 1), used as call-back at t_exception_propagation-x_declaration_parameter.adb:143:4
t_exception_propagation-x_declaration_parameter.adb:44:4: Error: Param12: subprogram "Proc12" can propagate exceptions (declaration at level 2), used as call-back at t_exception_propagation-x_declaration_parameter.adb:144:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param13: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:148:4
t_exception_propagation-x_declaration_parameter.adb:33:4: Error: Param13: subprogram "Proc11" can propagate exceptions (declaration at level 3), used as call-back at t_exception_propagation-x_declaration_parameter.adb:149:4
t_exception_propagation-x_declaration_parameter.adb:44:4: Error: Param13: subprogram "Proc12" can propagate exceptions (declaration at level 3), used as call-back at t_exception_propagation-x_declaration_parameter.adb:150:4
t_exception_propagation-x_declaration_parameter.adb:55:4: Error: Param13: subprogram "Proc13" can propagate exceptions (declaration at level 3), used as call-back at t_exception_propagation-x_declaration_parameter.adb:151:4
t_exception_propagation-x_declaration_parameter.adb:64:4: Error: Param10: subprogram "Proc2" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:153:4
t_exception_propagation-x_declaration_parameter.adb:72:4: Error: Param10: subprogram "Proc3" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:154:4
t_exception_propagation-x_declaration_parameter.adb:91:4: Error: Param10: generic "Gen1" can propagate exceptions, instance "Inst1" at t_exception_propagation-x_declaration_parameter.adb:95:4 used as call-back at t_exception_propagation-x_declaration_parameter.adb:155:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param4: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:157:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param4: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:158:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param2: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:160:4
t_exception_propagation-x_declaration_parameter.adb:27:4: Error: Param3: subprogram "Proc10" can propagate exceptions, used as call-back at t_exception_propagation-x_declaration_parameter.adb:162:4
t_exception_propagation-x_interface.adb:7:4: Error: interf: subprogram "Proc_C1" can propagate exceptions, interfaced to C
t_exception_propagation-x_interface.adb:11:4: Error: interf: subprogram "Proc_C2" can propagate exceptions, interfaced to C
t_exception_propagation-x_interface.adb:21:4: Error: interf: subprogram "Proc_C3" can propagate exceptions, interfaced to C
t_exception_propagation-x_interface.adb:33:4: Error: interf: subprogram "F" can propagate exceptions, interfaced to C
t_exception_propagation-x_task.adb:4:4: Error: task: task "T1" can propagate exceptions
t_exception_propagation-x_task.adb:19:4: Error: task: task "T3" can propagate exceptions
